apiVersion: v1
kind: Service
metadata:
  labels:
    app: mq
  name: mq-0
spec:
  ports:
  - name: mq-ext
    port: 1414
    protocol: TCP
    targetPort: 1414
  selector:
    app: mq
  sessionAffinity: None
  type: ClusterIP
