apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq
spec:
  template:
    spec:
      containers:
      - name: mq
        volumeMounts:
        - mountPath: /mnt/mqm
          name: mq-var-mqm
      volumes:
      - name: mq-var-mqm
        persistentVolumeClaim:
          claimName: mq-data
